name = "sample-cf-app"
compatibility_date = "2024-07-21"

[vars]
APP_NAME = "SAMPLE APP"

[dev]
port = 9000

[[kv_namespaces]]
binding = "article"
id = "533e14b65775464796b92daf7ebc65ac"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
