name = "sample-cf-api"
compatibility_date = "2024-07-21"

[vars]
APP_NAME = "SAMPLE APP"

[dev]
port = 9000

[[kv_namespaces]]
binding = "article"
id = "533e14b65775464796b92daf7ebc65ac"

[[services]]
binding = "KIRIBI" # Be sure to set KIRIBI for the service binding
service = "my-kiribi" # The name of the Kiribi my-kiribi
